GET http://localhost:9998/04_servlets_war_exploded/api/posts/6

###


GET http://localhost:9998/04_servlets_war_exploded/api/posts

###

POST http://localhost:9998/04_servlets_war_exploded/api/posts
Content-Type: application/json

{
  "content": "Last Post"
}

###
PATCH http://localhost:9998/04_servlets_war_exploded/api/posts/6
Content-Type: application/json

{
  "id": 6,
  "content": "Last Post patcjhed5dfdf______"
}

###

DELETE http://localhost:9998/04_servlets_war_exploded/api/posts/9